### ISSUE TITLE
Survey // As a user, I want to have my survey input saved as a draft, so I can come back to it at a later stage and finish the survey.

### ISSUE THREAD

**Issue by tassilomorino** [Senf-koeln/Main-App#108]
**Why?**
Better user experience (Citizen)
Higher rate of survey results (Organisation)

**Why now?**
Project in Wismar with urgent customer request for this functionality

**Acceptance Criteria:**

Everytime the user clicks on next, the survey input and the timestamp gets saved.
When the user closes the survey within the app, a notification is displayed to the user informing them about closing the survey and confirming that their survey input has been saved as a draft.
When the user closes the browser tab or shuts down their phone or computer, the survey input gets saved to the latest fully completed survey question,
The user can return to the survey at a later time and pick up where they left off.
The user gets directly linked to the latest unfinished question in the survey, when they click again on the “An Umfrage teilnehmen” button
The organization gets the amount of survey results per question displayed in the project hub.
The organization sees all survey inputs for fully completed questions displayed in the project hub, even if they do not finish the full survey.

Not in scope for now:

When the user didn’t finish the survey, the button changes to “Umfrage fortsetzen”
The user gets displayed on the idea overview how many questions they have answered

**Comment by rauscht** [comment]
modal when user closes survey: https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=7876%3A680868&t=5g13gupx8AT7rb5y-1

**Comment by rauscht** [comment]
Umfrage fortsetzen design proposal: https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=7876%3A680928&t=5g13gupx8AT7rb5y-1
