### ISSUE TITLE
Design & implement FAQ Section

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#115]
**Acceptance Criteria:**

- [ ] A FAQ is accessible from the main navigation
- [ ] The FAQ is tested with users and improved based on feedback.

———

**Value for stakeholders:**

Allows users to easily find answers to common questions, improving their experience with the platform.

———

**Helpful information for development team:**

The team should research and implement a FAQ that is easy for users to access and use. The team should test the FAQ with users to ensure it is effective and make improvements based on feedback.

———

**Possible work streams:**

- [ ] UX: Conduct user testing with the current design of the FAQ
- [ ] UI: Develop the design of the FAQ based on the user testing results
- [ ] UI: Decide on the position of the FAQ inside of the navigation
- [x] Programming: Implement the FAQ in the platform

———

**Possible testing strucutre:**

- [ ] Conduct user testing to ensure that the FAQ is easy to understand and find
- [ ] Verify that the FAQ is consistent across the platform

**Comment by lena-buehn** [comment]
Yesterday I tested the feedback function, FAQ and dropdown navigation. There are still a few minor things that need to be improved. Since I’m not available today, it should be ready for deployment by Thursday noon.

**Comment by lena-buehn** [comment]
You find the design in the “FAQ“ section on the following Figma page:

[https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=4096%3A269095](url)
