### ISSUE TITLE
City-Selection // As an organization I want to be able to find relevant information about the offer of Senf in order to consider Senf as my preferred choice

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#117]

**Comment by rauscht** [comment]
Prototype mobile for testing https://www.figma.com/proto/dmRMYzTiSFHopIK3LNbQXL/Senf?page-id=321%3A1783&node-id=8492%3A713384&viewport=4069%2C-1271%2C0.21&scaling=scale-down&starting-point-node-id=8492%3A713384&show-proto-sidebar=1

Screen mobile https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=8492%3A713277&t=ZvhKIlfyB5YVrOGJ-1

Screen Desktop https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=8523%3A702130&t=ZvhKIlfyB5YVrOGJ-1
