### ISSUE TITLE
Reconfigure the id's in the wismar-survey

### ISSUE THREAD

**Issue by tassilomorino** [Senf-koeln/Main-App#121]
The id's in the entries of the Wismar-survey have changed since the 24.1. Please align them back to the actual question id's of these questions.

Questions:

- 11
- 14
- 23
- 27
- 29
- 31

**Comment by lnvglr** [comment]
11: 33771f9c-1546-413c-8885-06592a58f7d2 → f38bf19d-079c-4d57-ba07-05aec15139d4
14: ea890f6a-2aef-47f6-9dc4-34344ca5188d → 5d6e987d-47be-43e2-a314-cda719570286
23: dbf4a808-f706-47d1-896f-f158d226b7b1 → 924aeeb7-aff8-4882-aa13-fcb7d0ec07ca
27: a84d99bd-ff88-49e8-8bd9-7d60bc4912df → f1bf6aa2-1a9b-492a-8021-44362e255cc6
29: fd8dfaf5-0e34-4ed8-aa41-346ae7ae4570 → 445e2bae-32f6-49be-a609-8d9cbd7f9524
31: d83bce1f-7789-4c69-8c0a-0a686c5da4f5  → 7032495e-fe80-4185-9322-efac0b088887

**Comment by lnvglr** [comment]
31: old: ba1e973b-b8b5-4ac6-95b2-1b5f398b1c97

**Comment by lnvglr** [comment]
function to replace question ids
```
// "old id": "new id"
const transformations = {
  // "33771f9c-1546-413c-8885-06592a58f7d2":
  //   "f38bf19d-079c-4d57-ba07-05aec15139d4",
  // "ea890f6a-2aef-47f6-9dc4-34344ca5188d":
  //   "5d6e987d-47be-43e2-a314-cda719570286",
  // "dbf4a808-f706-47d1-896f-f158d226b7b1":
  //   "924aeeb7-aff8-4882-aa13-fcb7d0ec07ca",
  // "a84d99bd-ff88-49e8-8bd9-7d60bc4912df":
  //   "f1bf6aa2-1a9b-492a-8021-44362e255cc6",
  // "fd8dfaf5-0e34-4ed8-aa41-346ae7ae4570":
  //   "445e2bae-32f6-49be-a609-8d9cbd7f9524",
  // "d83bce1f-7789-4c69-8c0a-0a686c5da4f5":
  //   "7032495e-fe80-4185-9322-efac0b088887",
};

const transformResults = async (entries: QuerySnapshot<DocumentData>) => {
  entries.forEach((e) => {
    const entry = { ...e.data() };
    Object.entries(transformations).forEach(([key, value]) => {
      if (entry.values?.[key]) {
        entry.values[value] = entry.values[key];
        delete entry.values[key];
      }
    });
    updateDoc(doc(db, e.ref.path), entry);
  });
};
```

**Comment by lnvglr** [comment]
- [x] TODO: check if answer uids persist
- [x] Check: everything stays the same when inserting questions
