### ISSUE TITLE
Accessibiliy // Ideacard: District-Header fails in contrast 

### ISSUE THREAD

**Issue by tassilomorino** [Senf-koeln/Main-App#139]
As a user with a visual handicap, I would like to be able to easily recognise the district heading on the ideacard to ensure accessibility.

![Bildschirmfoto 2023-02-02 um 15.47.19.png](https://images.zenhubusercontent.com/60f47913ad515f9e4c4346e5/80a5cf59-f44e-4d1c-b655-2108dd5819ed)

**Comment by rauscht** [comment]
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=3886%3A284903&t=DpLBQ67fuXyfAwcF-1
