### ISSUE TITLE
 Create a list of all the data points currently being tracked on the platform

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#152]
**Acceptance Criteria:**

- [x] The list of data points being tracked is comprehensive and includes all relevant information being collected
- [x] The list is organized in a clear and easy-to-understand manner
- [ ] The list includes a description of the data point, what it measures, and why it is relevant to track

**Comment by lena-buehn** [comment]
You'll find a list of all data points here: https://docs.google.com/spreadsheets/d/1mcKpOxKGMghvipX-mTpwn66xAMgrC4BLOexSKbvGvaE/edit#gid=0
