### ISSUE TITLE
Define and document the insights to be generated by the data collection process

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#153]
**Acceptance Criteria:**

- [ ] The team should have a clear understanding of the specific insights they want to gather from the collected data.

**Comment by lena-buehn** [comment]
You'll find a list of all data points here: https://docs.google.com/spreadsheets/d/1mcKpOxKGMghvipX-mTpwn66xAMgrC4BLOexSKbvGvaE/edit#gid=0

**Comment by christianwvh** [comment]
![image.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/0d7e1118-28f4-48f7-ab86-3bace13d25a1)
