### ISSUE TITLE
Draft the tag-adding feature: Create a design that shows how organizations will add tags to citizens' ideas in the project hub

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#178]

**Comment by christianwvh** [comment]
Liste mit potenziellen Idea-Tags für Planungsbüros:
https://docs.google.com/document/d/1Ybe5mqfsSaGtATUqmYRav8vUEksJihVGTPdZeYCk5HU/edit?usp=sharing

**Comment by rauscht** [comment]
list https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=5198%3A435664&t=j1rz5aC3i7fyXNJT-1

detail view https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=5494%3A440014&t=j1rz5aC3i7fyXNJT-1
