### ISSUE TITLE
Design the Marketing-Campaign-Manager overview including the Builder form

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#201]
MVP needed!

**Acceptance Criteria:**

- The organization can access the marketing-campaign-board from the Project Hub Dashboard.
- The marketing-campaign-board includes a Campaign URL Builder, which is a form within  a modal where the user can enter the title of the campaign and add parameters using a pre-defined convention.
- The parameters available in the form include source, medium, campaign, term, (and content?).
- The parameters will be added e.g. as dropdowns / input-field
- The form validates that all required parameters are filled in before allowing the user to generate the URL.
- The generated URL is displayed to the user in a marketing-campaign-board and can be copied to the clipboard.
- The marketing-campaign-board includes a tracking overview that shows information about the number of clicks and the conversion rate of registrations.

**Comment by tassilomorino** [comment]
[Uploading... Bildschirmfoto 2023-02-23 um 12.30.33.png]

**Comment by tassilomorino** [comment]
https://www.youtube.com/watch?v=O3QPk4LLeRQ&ab_channel=HubSpotTutorialsbywebdew

**Comment by tassilomorino** [comment]
https://www.youtube.com/watch?v=O3QPk4LLeRQ&ab_channel=HubSpotTutorialsbywebdew

**Comment by tassilomorino** [comment]
How it looks like in Hubspot: https://www.youtube.com/watch?v=O3QPk4LLeRQ&ab_channel=HubSpotTutorialsbywebdew

**Comment by tassilomorino** [comment]
The place where its meant to be at for the moment:

![Bildschirmfoto 2023-02-23 um 12.30.33.png](https://images.zenhubusercontent.com/60f47913ad515f9e4c4346e5/29c4398b-086e-4d7d-aedc-ee82c693fb7d)

**Comment by christianwvh** [comment]
**Medium:**

cpc (cost-per-click advertising)
banner (display advertising)
email (email marketing)
social (social media advertising)
referral (referral traffic)
organic (organic search traffic)
direct (direct traffic)


**Source:**

Google
Facebook
LinkedIn
Twitter
Instagram
YouTube
Bing
Yahoo

**Comment by lena-buehn** [comment]
A first draft can be found here:
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=9633%3A629846&t=591L2oXoXy6qHFCd-1

**Comment by lena-buehn** [comment]
@christianwvh what about print or merchandise sources? 
I still think that sources might be too specific for a drop-down selection. I would suggest to try out an input field for sources and a drop-down selection for the medium. what do think?
