### ISSUE TITLE
Design a way to display the information on how the ideas will be processed (thank you screen)

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#209]
- Also add a CTA -> Survey/Add Idea

**TEXT:**

Was passiert mit meinen Ideen und Antworten aus der Umfrage?

Wir freuen uns über Deine Umfragebeteiligung und Deine Ideen für Wismar! Mit Deinem Input hilfst Du uns dabei, konkrete Maßnahmen für die Zukunft der Wismarer Innenstadt abzuleiten. Wir werten alles gründlich aus und innerhalb eines mehrstufigen Prozesses, wird am Ende eine umfangreiche Konzeptstudie mit konkretem Maßnahmenkatalog zur Verbesserung der Aufenthaltsqualität und des Erlebnischarakters der Altstadt und des alten Hafens entstehen.

**Comment by rauscht** [comment]
app https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=9744%3A662237&t=eIDQFONG2BTWCGKw-1

dashboard https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=5408%3A400625&t=eIDQFONG2BTWCGKw-1
