### ISSUE TITLE
Design Cookie Configurator

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#224]

**Comment by rauscht** [comment]
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=9823%3A674589&t=7LyInDxSkiJgXhNF-1

**Comment by rauscht** [comment]
settings modal https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=9799%3A691859&t=7LyInDxSkiJgXhNF-1
