### ISSUE TITLE
Draft how to tell the user that the participation period has expired

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#234]
- Displayed when user clicks on idea/survey/like/comment in an expired project
- tooltips / disabled button / toast notification
- disable like/comment is very difficult - ask for relevance

**Comment by rauscht** [comment]
mobile https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10462%3A791027&t=zup8CmeVdl7xeVba-1
desktop https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=9795%3A665567&t=zup8CmeVdl7xeVba-1
