### ISSUE TITLE
Draft how the projectroom is displayed in the project hub

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#235]
- participation end not the same as expired
- projectrooms in project hub still relevant after the end of participation phase

**Comment by rauscht** [comment]
list https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=7138%3A625463&t=zup8CmeVdl7xeVba-1
project https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10462%3A815998&t=zup8CmeVdl7xeVba-1
