### ISSUE TITLE
Initial Benchmark - Maptionnaire Features

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#237]
Prio:
https://www.tetraeder.com/produkte_pb
https://maptionnaire.com/deutsch
—
http://klimakarte.terrifica.eu/
https://www.ushahidi.com/
https://survey123.arcgis.com/
https://www.citizenlab.co/en-us-trial
https://consulproject.nl/de/

**Comment by christianwvh** [comment]
1. Limited data on location-specific issues: Many issues are specific to a particular location, such as transportation patterns or environmental conditions. However, traditional surveys may not collect enough data on these issues, as they often rely on self-reported data that may not be specific to a particular location. Maptionnaire aims to solve this problem by allowing users to create surveys that include location-based questions, which can provide more precise and accurate data on location-specific issues.
2. Difficulty in visualizing location-based data: Location-based data can be difficult to visualize and analyze, especially if you are not familiar with the location in question. Maptionnaire provides tools for visualizing and analyzing location-based data, which can help users to understand the data more easily and communicate their findings to others.
3. Inefficient survey design: Traditional survey tools may not allow for efficient survey design, especially if you need to ask location-based questions. Maptionnaire's drag-and-drop interface allows users to design surveys quickly and easily, with features like survey logic and customizable question types that help to make the survey experience more efficient for both the respondent and the survey creator.
4. Limited language support: Many survey tools may not support multiple languages, which can make it difficult to collect data from a diverse range of respondents. Maptionnaire supports multiple languages, which can help to increase the accessibility of surveys and improve response rates.

**Comment by lena-buehn** [comment]
All information focusing on the survey can be found here:
https://www.notion.so/Focus-Survey-bd8318d1c7574d9494ce6fe590c7d5e5?pvs=4
