### ISSUE TITLE
Initial draft of user flow with optional log in

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#242]
- Meeting/ Alignment Dev & UX needed
- no big changes - minimal effort to just get it implemented

**Comment by christianwvh** [comment]
First draft

![image.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/944b4aa0-2e20-4615-a00c-f2cf7cc3012f)

**Comment by lena-buehn** [comment]
The draft looks great and makes sense. We should also keep in mind what happens afterwards. 
Probably the modal showing up to say thank's for participate to the survey or sharing an idea, might remind the user and say: stay informed via e-mail (if not submitted before) / create account / continue as guest
