### ISSUE TITLE
Draft map integration with survey questions

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#247]
- Integrate the map component with the survey questions, so that respondents can provide location-specific data in response to questions
- The map component should allow for various types of responses, such as selecting a point on the map, drawing a shape or path

**Comment by rauscht** [comment]
mobile design for citizen user https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10224%3A716127&t=20OoHwj0Ka4P5BfI-1

desktop design for citizen https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10238%3A693147&t=20OoHwj0Ka4P5BfI-1

**Comment by rauscht** [comment]
design exploration https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10286%3A697123&t=g5rnOXIVunN6t1aU-1
