### ISSUE TITLE
Draft map-based survey creation interface

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#248]
MVP needed!

- user-friendly interface that allows researchers to easily create surveys that include a map component
- The interface should be intuitive and easy to navigate, with clear instructions and prompts
- Conduct UX meeting

**Comment by rauscht** [comment]
create element for dashboard https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10020%3A701531&t=20OoHwj0Ka4P5BfI-1

mobile design for citizen user https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10224%3A716127&t=20OoHwj0Ka4P5BfI-1

desktop design for citizen https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10238%3A693147&t=20OoHwj0Ka4P5BfI-1
