### ISSUE TITLE
Implement new design to display expired projectrooms

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#316]

**Comment by rauscht** [comment]
list view https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=7138%3A627038&t=yKYFYJeWB3ji5Ejg-1
projectroom detail https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10462%3A815998&t=yKYFYJeWB3ji5Ejg-1
main app mobile (on the right end you find the implementation with the current design) https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10462%3A791027&t=yKYFYJeWB3ji5Ejg-1
main app desktop https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=4096%3A269095&t=yKYFYJeWB3ji5Ejg-1
