### ISSUE TITLE
Implement testing-findings in the tag-adding feature

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#320]
- show the already used tags as preselection when i want to add/type a new tag (e.g. in a small modal)
- no drag/drop delete –> better "x" next to tag-name
- horizontal scroll can be confusing (but normally there are only 1 and max. 3 tags)

- Open Question: Multiple tags possbile for excel export?

**Comment by rauscht** [comment]
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10532%3A765873&t=kp1stL0USvpm0Tkb-1
