### ISSUE TITLE
Create 2 more quick drafts (wireframes) of the tag adding feature

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#321]
- Benchmarking and documenting with other tools

**Comment by rauscht** [comment]
Why 2?

**Comment by rauscht** [comment]
simple version with last used tags in suggestions-list. https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10532%3A765873&t=kp1stL0USvpm0Tkb-1

advanced version with tag manager https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=10550%3A777269&t=02ROWvFthh9eUk6V-1
