### ISSUE TITLE
Design PDF-Upload in Project-Hub + display in Projectroom

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#400]
- it is possible to add max. X? PDF-files (?)
- it is possible to delete pdf files  
- it is mandatory to add a name to the pdf file  
—
- interview with customers needed

**Comment by rauscht** [comment]
the designs differ from the actual designs. there is no need to recreate the designs in detail, as we still do not have all the components used in the designs.

pdf upload https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?type=design&node-id=11332%3A727595&t=Zo0cjUYll8oG29br-1

info modal https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?type=design&node-id=6616%3A782324&t=Zo0cjUYll8oG29br-1
