### ISSUE TITLE
Finalize file component for PDF Upload

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#451]

**Comment by rauscht** [comment]
two line file list item https://www.figma.com/file/d2retb8vTVW0xdiQfsG9xe/Senf%3A-Components?type=design&node-id=547%3A32670&mode=design&t=POmJbwtXfPjVVB1N-1
single line file list item https://www.figma.com/file/d2retb8vTVW0xdiQfsG9xe/Senf%3A-Components?type=design&node-id=547%3A32670&mode=design&t=POmJbwtXfPjVVB1N-1
