### ISSUE TITLE
Idea (no location) // As a user, I want to post ideas without a specific location so that I can share something that is relevant to the entire city/projectroom area

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#46]
—

**Acceptance Criteria:**

- It's just as easy to find an idea without a location in the projectroom as it is to find an idea with a location 
- Ideas without location are not hidden by "Show ideas in area“
- On the idea details page, it can be seen that the idea applies to the entire city/projectroom area.
- If I post an idea I can see that an idea without a location is an idea for the entire city/projectroom area.

**Comment by rauscht** [comment]
"Ideas without location are not hidden by "Show ideas in area“"
Wie soll das gehen? Das würde bedeuten dass wir ortsunspezifische immer mit anzeigen, egal in welchem Kartenausschnitt. Das würde diese Ideen krass bevorzugen.

**Comment by christianwvh** [comment]
- Ideen mit Standort werden hingegen auch sehr bevorzugt, da sie über die Karte angezeigt werden
- Ideen, die ohne Ort, also für den gesamten Stadt/Projektraum Bereich angelegt werden, beziehen sich von der Logik auch auf jeden Bereich in der Karte
- Button "Show ideas in area“ könnte auch ausgeblendet werden, allerdings kann ich mir vorstellen, dass das bei großen Projekträumen möglicherweise auch fehlen würde

**Comment by rauscht** [comment]
desktop
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=4741%3A363702&t=u2OEV35XbW4oYtDh-1

mobile https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=4870%3A364713&t=u2OEV35XbW4oYtDh-1
card without location
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=4700%3A533201&t=u2OEV35XbW4oYtDh-1
