### ISSUE TITLE
Create Design for Image Choice Question

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#482]
**Acceptance Criteria**
- Planers can upload multiple images  
- It is possible to show images to citizens as a selection instead of text as a multiple/single choice question  
- no combination with map or image gallery  
- Planers can select Multi Image Module in survey creation  

![image.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/03e6fb14-d333-470b-a8ac-98860965c37a)

**Comment by rauscht** [comment]
image choice components https://www.figma.com/file/0SHDTdtWf9Ld0USyQ2oWth/Survey%3A-Sprint-01.08-14.08?type=design&node-id=2350%3A76762&mode=design&t=LOMFmUNm5CRG7r3l-1

image choice question type https://www.figma.com/file/0SHDTdtWf9Ld0USyQ2oWth/Survey%3A-Sprint-01.08-14.08?type=design&node-id=6%3A43301&mode=design&t=LOMFmUNm5CRG7r3l-1
