### ISSUE TITLE
Select City // As an organization, I want to make sure that every city is equally accessible when opening the platform so that no projectroom/city is prioritized

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#54]
**Acceptance Criteria**

- Selection option is displayed when the platform is opened for the first time
- Existing cities are clearly displayed
- The selected city is saved and can be changed later via the interface

**Comment by rauscht** [comment]
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=6434%3A567929&t=NGWjFpHqxV8FdaHC-1
