### ISSUE TITLE
Registration // As a user, i want to know which input fields are mandatory for me to fill in so that i am not left wondering what is required

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#55]
**Acceptance Criteria:**

- It is visible which input fields are mandatory
- 

![Bildschirmfoto 2022-11-24 um 11.47.43.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/20b2f8ee-7ece-4290-b88e-ae63020fcc64)

**Comment by rauscht** [comment]
Es sind doch alles Pflichtfelder ausser das Bild?

**Comment by rauscht** [comment]
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=6365%3A578029&t=Yvh29AE3AKzXR3Ep-1
