### ISSUE TITLE
Registration // As a user, I want to know why I need to provide my personal information to share/comment/like an idea

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#56]
**Acceptance Criteria**

- Further information about the "why" are available

Blindtext:
Complete your profile to get started
Your data will help generate demographic evaluations on the "fairness" of the participation process

![Bildschirmfoto 2022-11-24 um 11.54.55.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/116403a1-9378-4568-8c4f-373156a6e527)

**Comment by rauscht** [comment]
Wenns geht bitte bei Screenshots den ganzen Screen nehmen, nicht nur einen Ausschnitt für ein bessere Kontextverständnis.

**Comment by rauscht** [comment]
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=6434%3A567770&t=NGWjFpHqxV8FdaHC-1
