### ISSUE TITLE
Projectroom-Infopage // As an organization, I want to display buttons with direct links to the participation opportunities on my project info page so they are quickly accessible

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/Main-App#57]
**Acceptance Criteria**

- Buttons are fixed / always visible when scrolling

![Bildschirmfoto 2022-11-24 um 12.35.43.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/4889a834-eabb-437d-8613-23318c5feffa)

![Bildschirmfoto 2022-11-24 um 12.35.59.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/edfa0285-4573-4420-85e6-ca65aadd2046)

**Comment by rauscht** [comment]
Mobile:
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=1856%3A124569&t=VUiyk7GueAPoKnd6-1

Desktop:
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=5626%3A549338&t=VUiyk7GueAPoKnd6-1

**Comment by rauscht** [comment]
desktop
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=6208%3A547665&t=e1Vyq1OBE41EuYZs-1

mobile
https://www.figma.com/file/dmRMYzTiSFHopIK3LNbQXL/Senf?node-id=1856%3A124569&t=e1Vyq1OBE41EuYZs-1
